// <auto-generated />
using Metro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240901004820_IntiaLCreate")]
    partial class IntiaLCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Metro.Models.CairoMetro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("line1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CairoStations");
                });
#pragma warning restore 612, 618
        }
    }
}
