// <auto-generated />
using Metro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Metro.Models.Line1Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Line1Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StationName = "Helwan"
                        },
                        new
                        {
                            Id = 2,
                            StationName = "Ain Helwan"
                        },
                        new
                        {
                            Id = 3,
                            StationName = "Helwan University"
                        },
                        new
                        {
                            Id = 4,
                            StationName = "Wadi Hof"
                        },
                        new
                        {
                            Id = 5,
                            StationName = "Hadayek Helwan"
                        },
                        new
                        {
                            Id = 6,
                            StationName = "El Maasara"
                        },
                        new
                        {
                            Id = 7,
                            StationName = "Tora El Asmant"
                        },
                        new
                        {
                            Id = 8,
                            StationName = "Kozzika"
                        },
                        new
                        {
                            Id = 9,
                            StationName = "Tora El Balad"
                        },
                        new
                        {
                            Id = 10,
                            StationName = "Sakanat El Maadi"
                        },
                        new
                        {
                            Id = 11,
                            StationName = "Maadi"
                        },
                        new
                        {
                            Id = 12,
                            StationName = "Hadayek El Maadi"
                        },
                        new
                        {
                            Id = 13,
                            StationName = "Dar El Salam"
                        },
                        new
                        {
                            Id = 14,
                            StationName = "El Zahraa"
                        },
                        new
                        {
                            Id = 15,
                            StationName = "Mar Girgis"
                        },
                        new
                        {
                            Id = 16,
                            StationName = "El Malek El Saleh"
                        },
                        new
                        {
                            Id = 17,
                            StationName = "Al Sayeda Zeinab"
                        },
                        new
                        {
                            Id = 18,
                            StationName = "Saad Zaghloul"
                        },
                        new
                        {
                            Id = 19,
                            StationName = "Sadat"
                        },
                        new
                        {
                            Id = 20,
                            StationName = "Nasser"
                        },
                        new
                        {
                            Id = 21,
                            StationName = "Orabi"
                        },
                        new
                        {
                            Id = 22,
                            StationName = "Al Shohadaa"
                        },
                        new
                        {
                            Id = 23,
                            StationName = "Ghamra"
                        },
                        new
                        {
                            Id = 24,
                            StationName = "El Demerdash"
                        },
                        new
                        {
                            Id = 25,
                            StationName = "Manshiet El Sadr"
                        },
                        new
                        {
                            Id = 26,
                            StationName = "Kobri El Qobba"
                        },
                        new
                        {
                            Id = 27,
                            StationName = "Hammamat El Qobba"
                        },
                        new
                        {
                            Id = 28,
                            StationName = "Saray El Qobba"
                        },
                        new
                        {
                            Id = 29,
                            StationName = "Hadayeq El Zaitoun"
                        },
                        new
                        {
                            Id = 30,
                            StationName = "Helmeyet El Zaitoun"
                        },
                        new
                        {
                            Id = 31,
                            StationName = "El Matareyya"
                        },
                        new
                        {
                            Id = 32,
                            StationName = "Ain Shams"
                        },
                        new
                        {
                            Id = 33,
                            StationName = "Ezbet El Nakhl"
                        },
                        new
                        {
                            Id = 34,
                            StationName = "El Marg"
                        },
                        new
                        {
                            Id = 35,
                            StationName = "New El Marg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
